# Generated by Django 3.0.2 on 2020-03-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200315_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
