# Generated by Django 3.0.2 on 2020-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200315_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
