# Generated by Django 3.0.3 on 2020-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200413_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_no',
            field=models.CharField(max_length=10),
        ),
    ]
