# Generated by Django 3.0.3 on 2020-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200417_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
