# Generated by Django 3.0.2 on 2020-04-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200419_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='hw_name',
        ),
    ]
