# Generated by Django 3.0.2 on 2020-04-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_auto_20200424_0336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerInstructor',
        ),
        migrations.AddField(
            model_name='assignment',
            name='num_q',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnswerStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveSmallIntegerField(unique=True)),
                ('correct_ans', models.CharField(max_length=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Assignment')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
