# Generated by Django 3.0.2 on 2020-05-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200501_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'course')},
        ),
    ]
